run:
  output_directory_name: modeling/runs
  id: 116

dataset:
  name: ThingsTInd
  raw_data_directory_name: /data/metric_learning/datasets/things_raw
  data_directory_name: null
  version: psycho
  batch_size: 9999

preprocessing:
  name: IndexRemapPreprocessing

model:
  name: Psycho
  activation_fn: relu
  beta: 0.000001
  embedding_size: 128
  use_normalization: True
  loss_type: triplet
  margin: 0.5
  metric_mode: FCT/max

optimization:
  optimizer_type: adam
  initial_learning_rate: 0.001
  weight_decay: 0.0001
  evaluate_globally: False
  num_training_epochs: 100

use_gpu: True
