run:
  output_directory_name: modeling/runs
  id: 303

dataset:
  name: IHSJCTImg
  raw_data_directory_name: /data/metric_learning/datasets/ihsj_raw
  data_directory_name: null
  version: direct
  batch_size: 249

preprocessing:
  name: ResNetImagePreprocessing
  image_size: 224

model:
  name: ResNet50
  frozen_variables: bn
  num_nonlinearity_layers: 0
  embedding_size: 128
  loss_type: double_multisimilarity
  margin: 0.5
  alpha: 2.0
  beta: 40.0
  metric_mode: FCT/max

optimization:
  optimizer_type: adam
  initial_learning_rate: 0.0001
  weight_decay: 0.0001
  evaluate_globally: False
  num_training_epochs: 10

use_gpu: True
