run:
  output_directory_name: modeling/runs
  id: 331

dataset:
  name: IHSJCSE
  raw_data_directory_name: /data/metric_learning/datasets/ihsj_raw
  data_directory_name: modeling/intermediate/datasets/ihsjc_se
  version: source_embedding
  source_embeddings_id: pt_ste5
  batch_size: 249

preprocessing:
  name: ResNetImagePreprocessing
  image_size: 224

model:
  name: ResNet50
  frozen_variables: bn
  num_nonlinearity_layers: 0
  embedding_size: 128
  loss_type: relaxed_facenet
  triplet_weight_type: from_source_triplets
  margin: 0.5
  margin2: 0.0
  tau: 0.25
  semihard_loss_threshold: 0.0
  metric_mode: fraction_same_triplet_relation_thresholded/max

optimization:
  optimizer_type: adam
  initial_learning_rate: 0.000001
  weight_decay: 0.0001
  evaluate_globally: True
  num_training_epochs: 100

use_gpu: True
