run:
  output_directory_name: modeling/runs
  id: 521

dataset:
  name: YummlyTImg
  raw_data_directory_name: /data/metric_learning/datasets/yummly_raw
  data_directory_name: null
  version: direct
  different_splits: True
  batch_size: 60

preprocessing:
  name: ResNetImagePreprocessing
  image_size: 224

model:
  name: ResNet50
  frozen_variables: bn
  num_nonlinearity_layers: 0
  embedding_size: 128
  loss_type: triplet
  margin: 0.2
  metric_mode: FCT/max

optimization:
  optimizer_type: adam
  initial_learning_rate: 0.0001
  weight_decay: 0.0001
  evaluate_globally: False
  num_training_epochs: 10

use_gpu: True
