run:
  output_directory_name: modeling/runs
  id: 661

dataset:
  name: YummlySE
  raw_data_directory_name: /data/metric_learning/datasets/yummly_raw
  data_directory_name: modeling/intermediate/datasets/yummly_se
  version: source_embedding
  source_embeddings_id: pt_ste5
  different_splits: True
  batch_size: 228

preprocessing:
  name: ResNetImagePreprocessing
  image_size: 224

model:
  name: Inception
  frozen_variables: bn
  num_nonlinearity_layers: 0
  embedding_size: 128
  loss_type: rkd
  metric_mode: fraction_same_triplet_relation_thresholded/max

optimization:
  optimizer_type: adam
  initial_learning_rate: 0.000001
  weight_decay: 0.0001
  evaluate_globally: True
  num_training_epochs: 100

use_gpu: True
